### ISSUE TITLE
how to use with AppImage?

### ISSUE THREAD

**Issue by MoorPoor** [lupin3rd/vimix-chataigne-module#1]
Thank you for pointing this amazing software out again!
I`m totally new to this topic and wonder how to add this module to an AppImage on Linux.
When I unpack the image I find another folder structure.

Or will it end up as a community module soon?

Thanks so much!

**Comment by MoorPoor** [comment]
Me fool!
sorry, I did not noticed that there is actually a folder in Documents/Chataigne.
I just did not expected it to be created there ;)

Testing now the module.
thanks again an sorry!

**Comment by lupin3rd** [comment]
No problem.
