### ISSUE TITLE
filter section problems

### ISSUE THREAD

**Issue by MoorPoor** [lupin3rd/vimix-chataigne-module#4]
EDIT: Sorry, I missed to update vimix to newest beta.... I will leave this post just in case someone else doing the same fault

thanks for the update.

Unfortunately, the filter section doesn't transmit to vimix. the other parameters do.
as you can see blur filter gets no values:
![Bildschirmfoto vom 2024-02-20 00-17-59](https://github.com/lupin3rd/vimix-chataigne-module/assets/60827766/8e442143-ebd7-490e-bbab-574c59d20ab6)

When changing the filter, the sliders are simply added. they are becoming more and more :)
![Bildschirmfoto vom 2024-02-20 00-25-14](https://github.com/lupin3rd/vimix-chataigne-module/assets/60827766/5ef923ba-8c3c-41ea-8dbb-f7d71f09c103)

I `m using ubuntu 23.10

**Comment by MoorPoor** [comment]
AH...
my mistake! again... :(
I probably don't have the right vimix beta running.
I will try again soon!

**Comment by lupin3rd** [comment]
Yes. You need last beta.

**Comment by lupin3rd** [comment]
> AH... my mistake! again... :( I probably don't have the right vimix beta running. I will try again soon!

Do you test with last beta of Vimix?
