### ISSUE TITLE
OSC command for controlling "Batch#" sources changes to lower case "batch#"

### ISSUE THREAD

**Issue by ThomZenTury** [lupin3rd/vimix-chataigne-module#6]
Hi there!
Thanks for the very useful module you created.
I just wanted to tell you that in the latest version of VIMIX (0.8.2) the OSC command for controlling batches changed an upper case to a lower case letter. I manually changed all the "Batch#" entries in your  vimix.js file and everything works as expected.
For anyone having issues with controlling VIMIX batches via Chataigne and this module:

- after copying and extracting the .zip to ".../Documents/Chataigne/modules" open the "vimix.js" file
- do a search for all "Batch#" entries and replace them with "batch#" (notice the lower case 'b' here)
- reload the module in Chataigne again (if already running)
- good to go again!

Have a nice day and thanks again for your efforts! 
Really handy and useful to get started with Chataigne!

**Comment by lupin3rd** [comment]
Hi!
Thanks for reporting the issue.
I fix in #7 .
I'm happy to hear that someone is using this module! Vimix and Chataigne are two excellent software!
